# Site settings
description: sudo apt-get install nails
baseurl: ""
url: "https://marsty5.github.io" 

# User settings
username: Nail Biting Independence
user_description: "Software Engineer involved in startups, data, traveling and teaching"
user_title: The journey begins with a bundle of joy
twitter_username: marsty5
github_username:  marsty5

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
